### Spring properties

# HTTP Server (Tomcat) Port
server: 
  port: 8763
  
# Service registers under this name
spring:
  application:
    name: apigateway

eureka:
  instance:
    hostname: localhost
  client: 
    registerWithEureka: true
    fetchRegistry: true  
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




    
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'  
  routes:
    user-service:
     path: /user/**
     serviceId: user-service 
     strip-prefix: true

